application:
  name: vana1
  project: vana1-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "12"
  name: my-psql
routers:
- name: main
  routes:
  - application_name: vana1
    paths:
    - /
